package com.matthew_savage;

public enum Values {
    GENRE_1 ("Action"),
    GENRE_DESC_1 ("Action is about conflict. Whether with guns, blades, fists, or mysterious powers, these titles feature characters in combat - either to protect themselves or the things or people they value, or simply as a way of life"),
    GENRE_2 ("Adult"),
    GENRE_DESC_2 ("Contains content that is suitable only for adults. Titles in this category may include prolonged scenes of intense violence and/or graphic sexual content and nudity"),
    GENRE_3 ("Adventure"),
    GENRE_DESC_3 ("In these titles, characters embark on a journey to explore the world or to search for something. These wanderers travel to many places and meet new people, often encountering hardships along the way, or discovering strengths and weaknesses about themselves that are revealed throughout the adventure"),
    GENRE_4 ("Comedy"),
    GENRE_DESC_4 ("These titles aim to make you laugh through satire, parody, humorous observations, slapstick scenarios, or absurd antics. Bonus points for spitting your drink all over your screen!"),
    GENRE_5 ("Cooking"),
    GENRE_DESC_5 ("Cooking, baking and drink making are the focus of these titles. Whether the characters within attend a Culinary School, work in a Restaurant or are simply passionate home cooks, these manga showcase step-by-step instructions on how to create a dish, often including a full recipe complete with images. Different techniques, historical facts, plating ideas, or general appreciation for food and the art of cooking are frequent themes in these manga"),
    GENRE_6 ("Doujinshi"),
    GENRE_DESC_6 ("Doujin are a popular type of independently produced and distributed magazine, generally made in small print runs and often written by fans of manga and/or anime, including fan-fiction based on pre-existing characters from other authors. Common themes in these titles include production and distribution, attending doujinshi conventions, or the culture of doujin readers"),
    GENRE_7 ("Drama"),
    GENRE_DESC_7 ("Drama manga heavily emphasize their characters' emotional development. Whether by experiencing the protagonist’s emotional turmoil, viewing heated character interactions, or exploring a passionate romance, any manga that humanizes its characters through emphasizing their flaws qualifies as a Drama"),
    GENRE_8 ("Ecchi"),
    GENRE_DESC_8 ("Constant panty shots, bouncing breasts and dubious camera angles are hallmarks of an Ecchi title. These titles are usually sexualized and designed to titillate, depicting perverted themes and focusing heavily on the female body. Nosebleeds, suspicious hand positions, faceplanting into bosoms, expressive and exaggerated body parts and other tropes characterize this genre. Ecchi is all about fanservice, while borderline H/smut titles focus more on sexual content"),
    GENRE_9 ("Fantasy"),
    GENRE_DESC_9 ("Fantasy titles take place in a broad range of settings influenced by mythologies, legends, or popular and defining works of the genre such as The Lord of the Rings. They are generally characterized by a low level of technological development, though fantasy stories can just as easily take place in our modern world, or in a post-apocalyptic society where technology was buried alongside the old world. These titles also tend to feature magic or other extraordinary abilities, strange or mysterious creatures, or humanoid races which coexist with humanity or inhabit their own lands removed from ours"),
    GENRE_10 ("Gender bender"),
    GENRE_DESC_10 ("A character in these titles undergoes a complete or partial physical sex change, whether due to environmental aspects, an enchanted item, a wish that's been granted or a number of other factors. Depending on the situation, the character might be stuck in their new body, or changed back automatically at some point, or have the ability to change back and forth at will. If a man and woman suddenly share the same body, the Gender Bender tag applies as well"),
    GENRE_11 ("Harem"),
    GENRE_DESC_11 ("A harem includes three or more characters who potentially show romantic interest in a male protagonist. The sex, gender, or orientation of the harem members is irrelevant as long as they exclusively, or at least primarily, are vying for the affections of the same individual - who may or may not reciprocate towards one, several, or none of these romantic rivals"),
    GENRE_12 ("Historical"),
    GENRE_DESC_12 ("The setting of a historical titles takes place at some point in Earth's past. The level of dedication to portraying the lifestyles, societies, and technologies of past periods and peoples accurately or believably can vary greatly between different works"),
    GENRE_13 ("Horror"),
    GENRE_DESC_13 ("Horror titles create an atmosphere of unease. Like a mystery, they encourage viewers to learn more about their world... but there may be secrets that are better left unexplored. Through eerie music and sounds, visceral or disturbing imagery, or startling moments, works of Horror make you worry about what gruesome thing is coming next"),
    GENRE_14 ("Josei"),
    GENRE_DESC_14 ("Josei, translated as \"woman\", is a demographic aimed at women from late teens through adulthood. These titles tend to be more mature, often focusing on realistic situations such as work life or romance"),
    GENRE_15 ("Manhua"),
    GENRE_DESC_15 ("These titles usually have original Chinese dialogue and/or were first released in China"),
    GENRE_16 ("Manhwa"),
    GENRE_DESC_16 ("These titles usually have original Korean dialogue and/or were first released in Korea"),
    GENRE_17 ("Martial arts"),
    GENRE_DESC_17 ("Characters in these titles attend a Martial Arts School where they learn one or more specialized Martial Arts forms. Competitions and power struggles are a common occurrence in these titles"),
    GENRE_18 ("Mature"),
    GENRE_DESC_18 ("These titles include mature or controversial topics that are not suitable for children, such as teen pregnancy, sexual abuse, prostitution, drug use, or others"),
    GENRE_19 ("Mecha"),
    GENRE_DESC_19 ("Mecha are self-propelling machines that are modeled after humans; some can change into multiple, non-humanoid formats as well. They're usually controlled by an internal pilot or by remote, but are sometimes sentient beings that move autonomously. A mecha's size ranges from bulky, wearable armor to a massive, towering contraption and beyond. While mecha have a wide range of applications, such as making manual labor easier, they are most commonly portrayed as heavily-armed war machines"),
    GENRE_20 ("Medical"),
    GENRE_DESC_20 ("These titles feature medical professionals such as doctors, surgeons and other staff, as they perform their medical duties at hospitals, clinics, or other locations"),
    GENRE_21 ("Mystery"),
    GENRE_DESC_21 ("Mystery titles focus on unresolved questions, and the efforts of characters to discover the answers to them. Whether curious and deadly events are afoot, or some part of the world itself is strange or inexplicable, or someone's past or identity seems strangely shrouded, these characters are set on learning the truth"),
    GENRE_22 ("One Shot"),
    GENRE_DESC_22 ("A One Shot is a single, standalone title that tells a complete story in roughly 15-60 pages. While the majority of the time they consist of a single chapter, One Shots are occasionally several chapters long. One Shots are often released to gauge interest in a full series, in which case they’re also labeled as Pilot Chapters. If popular, these Pilot Chapter/One Shots are serialized into a full series."),
    GENRE_23 ("Psychological"),
    GENRE_DESC_23 ("Psychological titles delve into mental or emotional states of a character in the midst of a difficult situation, letting you observe them change as tension increases. Internal monologues are a key feature, allowing narration to delve into a character's mind, revealing their innermost ideas and motivations - even as they may be driven to the brink of sanity"),
    GENRE_24 ("Romance"),
    GENRE_DESC_24 ("These titles showcase the joys and hardships of falling in love, whether a schoolgirl has an unrequited crush on her senpai, a Love Triangle occurs within a group of friends, or rivals become lovers through competition or their intense passion for each other"),
    GENRE_25 ("School Life"),
    GENRE_DESC_25 ("These titles showcase events that occur on a daily basis in a school, whether from the perspective of a student or of a teacher. Having fun in the classroom, attending school clubs, spending time with friends or doing daily chores are frequent themes in these titles"),
    GENRE_26 ("Sci fi"),
    GENRE_DESC_26 ("Sci-fi, or science fiction, is a speculative genre which builds on imagination. Sci-fi titles ask, \"what if things were different?\" They explore a new world, whether it's the world of the future or past, a present Earth with a changed history, a land that was previously unknown, or another planet entirely. The genre commonly features humanity's inquisitiveness and innovation, as they grapple with new technologies, new societies, or new frontiers in Outer Space"),
    GENRE_27 ("Seinen"),
    GENRE_DESC_27 ("Seinen, translated as \"youth\", is a demographic aimed at men from late teens to adulthood who understand kanji. Seinen manga rarely include furigana with kanji, and have a wide variety of topics and themes"),
    GENRE_28 ("Shoujo"),
    GENRE_DESC_28 ("Shoujo, translated as \"young woman\", is a demographic aimed at teenage girls. The most iconic and influential Shoujo character designs come from the early 20th century, where girls and boys alike were drawn with huge eyes"),
    GENRE_29 ("Shoujo ai"),
    GENRE_DESC_29 ("Yuri is a genre that depicts homosexual relationships between women. Japan typically uses this single category for all forms of these relationships, sexual or not. In the West, the term Shoujo-ai categorizes stories that focus on the emotional aspects of the relationships, while Yuri categorizes more of the sexual aspects and explicit content"),
    GENRE_30 ("Shounen"),
    GENRE_DESC_30 ("Shounen, translated as \"young boy\", is a demographic aimed at boys and young men, from elementary school age to around the age of 15"),
    GENRE_31 ("Shounen ai"),
    GENRE_DESC_31 ("Yaoi, known as Boys' Love or BL in Japan, is a genre mostly written by women, for women, that depicts homosexual relationships between men. Japan typically uses this single category for all forms of these relationships, sexual or not. In the West, the term Shounen-ai categorizes stories that focus on the emotional aspects of the relationships, while Yaoi categorizes more of the sexual aspects and explicit content"),
    GENRE_32 ("Slice of life"),
    GENRE_DESC_32 ("Slice of life, or \"nichijou\" in Japanese, refers to events that occur on a daily basis such as getting ready for the day, light chores, enjoying a hobby, or preparing meals. These events differ depending on setting, but above all else are considered to be ordinary, everyday actions that don’t always follow a central plot. The related tags School Life and Work Life focus on ordinary events that take place in a school or work setting, respectively."),
    GENRE_33 ("Smut"),
    GENRE_DESC_33 ("Smut anime are typically written by women, for women, for genres like Shoujo, Josei, and Yaoi. There's a strong focus on seduction, characters being swept off their feet, and other buildups to having sex that make you feel hot and bothered. Smutty anime frequently, but not always, includes explicit sexual content."),
    GENRE_34 ("Sports"),
    GENRE_DESC_34 ("These anime delve into the world of competitive Sports, ranging from team-based to individual participants. From Baseball or Basketball, to track and field or combat-based sports, these works focus on the athletes and those around them who show their support."),
    GENRE_35 ("Supernatural"),
    GENRE_DESC_35 ("Also called paranormal, supernatural events are those modern science has difficulty explaining. Supernaturally oriented titles are often steeped in folklore, myth, or Urban Legend. They may involve strange or inexplicable phenomena, Psychic Powers or emanations, and/or ghosts or other fantastic creatures. Supernatural events are those that lie at the edge of our understanding - they are easy to believe in, but difficult to prove."),
    GENRE_36 ("Tragedy"),
    GENRE_DESC_36 ("Events which show large mounts of misfortune and/or loss. May include character death."),
    GENRE_37 ("Webtoons"),
    GENRE_DESC_37 ("Webtoon is a term used to describe South Korean webcomics or manhwa that are published online."),
    GENRE_38 ("Yaoi"),
    GENRE_DESC_38 ("Yaoi, also known as Boys' Love or BL in Japan, is a genre mostly written by women, for women, that depicts homosexual relationships between men. Japan typically uses this single category for all forms of these relationships, sexual or not. In the West, the term Shounen-ai categorizes stories that focus on emotional aspects of relationships, while Yaoi categorizes more of the sexual aspects, such as Smut, or explicit content. As Anime-Planet's audience is mostly based in the West, we use the Western definition for both Yaoi and Shounen-ai. See BL for a list of both titles."),
    GENRE_39 ("Yuri"),
    GENRE_DESC_39 ("Yuri is a genre that depicts homosexual relationships between women. Japan typically uses this single category for all forms of these relationships, sexual or not. In the West, the term Shoujo-ai categorizes stories that focus on the emotional aspects of the relationships, while Yuri categorizes more of the sexual aspects and explicit content. As Anime-Planet's audience is mostly based in the West, we use the Western definition for both Yuri and Shoujo-ai."),
    STAT_PRE_TITLE_TOT ("My reader has "),
    STAT_SUF_TITLE_TOT (" total manga titles."),
    STAT_PRE_READING_TOT ("I'm presently reading "),
    STAT_SUF_READING_TOT (" manga titles."),
    STAT_PRE_FIN_TOT ("I've finished reading "),
    STAT_SUF_FIN_TOT (" manga titles."),
    STAT_PRE_PAGES_TOT ("I've read "),
    STAT_SUF_PAGES_TOT (" pages of manga."),
    STAT_PRE_FAVE_TOT ("I've favorited "),
    STAT_SUF_FAVE_TOT (" sublime manga titles."),
    STAT_PRE_BL_TOT ("I've blacklisted "),
    STAT_SUF_BL_TOT (" dreadful manga titles."),
    STAT_PRE_PAGES_DAY ("I read an average of "),
    STAT_SUF_PAGES_DAY (" pages per day."),
    STAT_PRE_GEN_ONE ("My favorite genre is "),
    STAT_PRE_GEN_TWO ("My second favorite genre is "),
    STAT_PRE_GEN_THREE ("My third favorite genre is "),
    DB_NAME_SETTINGS ("usr.db"),
    DB_NAME_MANGA ("main.db"),
    DB_NAME_DOWNLOADING ("downloads.db"),
    DB_TABLE_AVAILABLE ("available_manga"),
    DB_TABLE_COMPLETED ("completed"),
    DB_TABLE_READING ("currently_reading"),
    DB_TABLE_DOWNLOAD ("downloading"),
    DB_TABLE_NOT_INTERESTED ("not_interested"),
    DB_TABLE_BOOKMARK ("bookmark"),
    DB_TABLE_NEW_CHAPTERS ("new_chapters"),
    DB_TABLE_STATS ("stats"),
    DB_TABLE_VERSION ("version_number"),
    DB_COL_ID ("title_id"),
    DB_COL_TITLE ("title"),
    DB_COL_AUTH ("authors"),
    DB_COL_STATUS ("status"),
    DB_COL_STATUS_VAL_DONE ("Completed"),
    DB_COL_STATUS_VAL_NOT_DONE("Ongoing"),
    DB_COL_SUMM ("summary"),
    DB_COL_URL ("web_address"),
    DB_COL_GENRE ("genre_tags"),
    DB_COL_CHAP_TOT ("total_chapters"),
    DB_COL_CUR_PAGE ("current_page"),
    DB_COL_LAST_CHAP_READ ("last_chapter_read"),
    DB_COL_LAST_CHAP_DL ("last_chapter_downloaded"),
    DB_COL_NEW_CHAP_BOOL ("new_chapters"),
    DB_COL_ENT ("entry_number"),
    DB_COL_FAVE_BOOL ("favorite"),
    DB_VER_COL_VER ("version"),
    DB_STATS_COL_TITLE_TOT ("titles_total"),
    DB_STATS_COL_READING_TOT("reading_total"),
    DB_STATS_COL_FIN_TOT ("finished_reading"),
    DB_STATS_COL_PAGES_TOT ("pages_read"),
    DB_STATS_COL_FAVE_TOT ("favorites"),
    DB_STATS_COL_BL_TOT ("blacklisted"),
    DB_STATS_COL_PAGES_DAY ("pages_daily"),
    DB_STATS_COL_GEN_ONE ("first_genre"),
    DB_STATS_COL_GEN_TWO ("second_genre"),
    DB_STATS_COL_GEN_THREE ("third_genre"),
    DB_ATTACHED_PREFIX ("main."),
    DB_ATTACHED_AVAILABLE ("main.available_manga"),
    DB_ATTACHED_READING ("main.currently_reading"),
    DB_ATTACHED_DOWNLOADING ("downloadDb.downloading"),
    //    DIR_ROOT (GetApplicationPath.getPath()),  //live dir
    DIR_ROOT  ("C:\\Users\\Apple Laptop\\Documents\\reader"),  //development dir
//    DIR_ROOT  ("C:\\Users\\Apple\\Cupcaked Manga Reader"),  //development dir
    DIR_MANGA ("manga"),
    DIR_DB  ("data"),
    DIR_THUMBS ("thumbs"),
    URL_ROOT ("https://manganelo.com/"),
    URL_SEARCH ("search/");

    private String value;

    Values(String valueString) {
        this.value = valueString;
    }

    public String getValue() {
        return value;
    }
}
